In [1]:
using DelimitedFiles

In [2]:
wikiEVDraw = DelimitedFiles.readdlm("wikipediaEVDraw.csv", ',')

54×9 Array{Any,2}:
 "25 Nov 2015"  28637  11314  3804  2536  …  4808     14122     3955   
 "18 Nov 2015"  28634  11314  3804  2536     4808     14122     3955   
 "11 Nov 2015"  28635  11314  3805  2536     4808     14122     3955   
 "4 Nov 2015"   28607  11314  3810  2536     4808     14089     3955   
 "25 Oct 2015"  28539  11298  3806  2535     4808     14061     3955   
 "18 Oct 2015"  28476  11298  3803  2535  …  4808     14001     3955   
 "11 Oct 2015"  28454  11297  3800  2534     4808     13982     3955   
 "27 Sep 2015"  28388  11296  3805  2533     4808     13911     3955   
 "20 Sep 2015"  28295  11295  3800  2532     4808     13823     3955   
 "13 Sep 2015"  28220  11291  3792  2530     4808     13756     3953   
 "6 Sep 2015"   28147  11291  3792  2530  …  4808     13683     3953   
 "30 Aug 2015"  28073  11290  3792  2529     4808     13609     3953   
 "16 Aug 2015"  27952  11284  3786  2524     4808     13494     3952   
 ⋮                                        ⋱  

In [3]:
? read

search: read read! readdir readdlm readlink readline readuntil readlines



```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String`.

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004a (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [4]:
using Dates

In [7]:
Dates.DateTime(wikiEVDraw[1,1], "d u y")

2015-11-25T00:00:00

In [8]:
for num = 3:7
    println("num is now $num")
end

num is now 3
num is now 4
num is now 5
num is now 6
num is now 7


In [9]:
testvalues =[23, "my name is not a name", 'ℵ']
for x in testvalues
    println("The value of x is now: $x")
end

The value of x is now: 23
The value of x is now: my name is not a name
The value of x is now: ℵ


In [10]:
col1 = wikiEVDraw[:,1]

54-element Array{Any,1}:
 "25 Nov 2015"
 "18 Nov 2015"
 "11 Nov 2015"
 "4 Nov 2015" 
 "25 Oct 2015"
 "18 Oct 2015"
 "11 Oct 2015"
 "27 Sep 2015"
 "20 Sep 2015"
 "13 Sep 2015"
 "6 Sep 2015" 
 "30 Aug 2015"
 "16 Aug 2015"
 ⋮            
 "9 Aug 2014" 
 "30 Jul 2014"
 "23 Jul 2014"
 "14 Jul 2014"
 "2 Jul 2014" 
 "17 Jun 2014"
 "27 May 2014"
 "12 May 2014"
 "1 May 2014" 
 "14 Apr 2014"
 "31 Mar 2014"
 "22 Mar 2014"

In [11]:
for i in 1:length(col1)
    col1[i] = Dates.DateTime(col1[i], "d u y")
end

In [12]:
col1

54-element Array{Any,1}:
 2015-11-25T00:00:00
 2015-11-18T00:00:00
 2015-11-11T00:00:00
 2015-11-04T00:00:00
 2015-10-25T00:00:00
 2015-10-18T00:00:00
 2015-10-11T00:00:00
 2015-09-27T00:00:00
 2015-09-20T00:00:00
 2015-09-13T00:00:00
 2015-09-06T00:00:00
 2015-08-30T00:00:00
 2015-08-16T00:00:00
 ⋮                  
 2014-08-09T00:00:00
 2014-07-30T00:00:00
 2014-07-23T00:00:00
 2014-07-14T00:00:00
 2014-07-02T00:00:00
 2014-06-17T00:00:00
 2014-05-27T00:00:00
 2014-05-12T00:00:00
 2014-05-01T00:00:00
 2014-04-14T00:00:00
 2014-03-31T00:00:00
 2014-03-22T00:00:00

In [13]:
Dates.datetime2rata(col1[1])

735927

In [15]:
length(col1)

54

In [43]:
dayssincemar22(x) = Dates.datetime2rata(x) - Dates.datetime2rata(col1[length(col1)])

dayssincemar22 (generic function with 1 method)

In [44]:
epidays = Array{Int64}(undef,length(col1))

54-element Array{Int64,1}:
 140551992378512
 140551992378560
 140551992378608
 140551992378656
 140551992378704
 140551992378752
 140551992378800
 140551992378848
 140551992378896
 140551992378992
 140551992379040
 140551992379088
 140551992379136
               ⋮
 140551985410928
 140551985411024
 140551985411072
 140551985411120
 140551985411168
 140551985411216
 140551985411264
 140551985411312
 140551985411360
 140551985411408
 140551985411456
 140551985411504

In [45]:
for i = 1:length(col1)
    epidays[i] = dayssincemar22(col1[i])
    #println(dayssincemar22(col1[i]))
end

In [46]:
epidays

54-element Array{Int64,1}:
 613
 606
 599
 592
 582
 575
 568
 554
 547
 540
 533
 526
 512
   ⋮
 140
 130
 123
 114
 102
  87
  66
  51
  40
  23
   9
   0

In [47]:
wikiEVDraw[:,1] = epidays

54-element Array{Int64,1}:
 613
 606
 599
 592
 582
 575
 568
 554
 547
 540
 533
 526
 512
   ⋮
 140
 130
 123
 114
 102
  87
  66
  51
  40
  23
   9
   0

In [62]:
wikiEVDraw[7,:]

9-element Array{Any,1}:
   568
 28454
 11297
  3800
  2534
 10672
  4808
 13982
  3955

In [49]:
DelimitedFiles.writedlm("wikipediaEVDdatesconverted.csv",wikiEVDraw,',')

In [58]:
mylist = [3, 2, 1]
countc=1
for i in mylist
    println(countc,i)
    mylist[i]=countc
    countc=countc+1
end

13
22
31


In [59]:
mylist[3]

1

In [60]:
function test(x)
    if x==1 
        return 1
    end
    if x<=0
        return 0
    end
    return test(x-1)+test(x-2)
end
test(3)

2

In [64]:
summedvals = 3
for k = 1:2:5  
    println(k)
    summedvals = summedvals + k
end
summedvals

1
3
5


12