In [1]:
greeting = "Hello world"
println(greeting)

Hello world


In [2]:
a,b,c = cos(0.2), log(10), abs(-1.22)

(0.9800665778412416, 2.302585092994046, 1.22)

In [3]:
a

0.9800665778412416

In [4]:
? cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos const close isconst



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [5]:
cos(0)

1.0

In [6]:
cos(π)

-1.0

In [11]:
cos(π/2)

6.123233995736766e-17

In [13]:
typeof(π)

Irrational{:π}

In [15]:
methods(muladd)

# 12 methods for generic function "muladd":
[1] muladd(a::Float16, b::Float16, c::Float16) in Base at float.jl:406
[2] muladd(x::Float64, y::Float64, z::Float64) in Base at float.jl:404
[3] muladd(x::Float32, y::Float32, z::Float32) in Base at float.jl:403
[4] muladd(z::Complex, w::Complex, x::Complex) in Base at complex.jl:272
[5] muladd(x::Real, z::Complex, y::Number) in Base at complex.jl:315
[6] muladd(z::Complex, x::Real, y::Real) in Base at complex.jl:316
[7] muladd(z::Complex, x::Real, w::Complex) in Base at complex.jl:317
[8] muladd(x::Real, y::Real, z::Complex) in Base at complex.jl:319
[9] muladd(z::Complex, w::Complex, x::Real) in Base at complex.jl:320
[10] muladd(x::T, y::T, z::T) where T<:Number in Base at promotion.jl:397
[11] muladd(x::Number, y::Number, z::Number) in Base at promotion.jl:348
[12] muladd(x, y, z) in Base.Math at math.jl:1012

In [16]:
myfunc(firstvar) = 20* firstvar

myfunc (generic function with 1 method)

In [18]:
myfunc(333.2222)

6664.4439999999995

In [19]:
addxtoy(x,y) = x + y

addxtoy (generic function with 1 method)

In [20]:
addxtoy(22,-3.2)

18.8

In [21]:
function nextfunc(x,y,z)
     x+y*z
end

nextfunc (generic function with 1 method)

In [22]:
function showdebugprintln(testvar)
    println("Show inside the showdebugprintln() now")
    println("The type of testvar is $(typeof(testvar)) and the value of testvar is $testvar")
end

showdebugprintln (generic function with 1 method)

In [23]:
a = ['1',2.]

2-element Array{Any,1}:
  '1'
 2.0 

In [24]:
showdebugprintln(a)

Show inside the showdebugprintln() now
The type of testvar is Array{Any,1} and the value of testvar is Any['1', 2.0]


In [28]:
mycos(x) = cos(x)

mycos (generic function with 1 method)

In [29]:
mycos(.3)

0.955336489125606

In [30]:
mycos(adj,hyp) = adj/hyp

mycos (generic function with 2 methods)

In [32]:
mycos(12,13)

0.9230769230769231

In [31]:
methods(mycos)

# 2 methods for generic function "mycos":
[1] mycos(x) in Main at In[28]:1
[2] mycos(adj, hyp) in Main at In[30]:1

In [33]:
mycos(thet::Float64) = cos(thet)

mycos (generic function with 3 methods)

In [34]:
60 \ 5040

84.0

In [35]:
? \

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [36]:
5040/60

84.0

In [38]:
addone(x::Int64) = x+1

addone (generic function with 1 method)

In [42]:
addone(ceil(1.2)*10)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[38]:1

In [43]:
a,b=1,2

(1, 2)

In [44]:
a,b=b,a

(2, 1)

In [46]:
a

2

In [47]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [48]:
typeof(test(2))

22


Nothing

In [56]:
add2(x,y) = return x + y

add2 (generic function with 1 method)

In [57]:
println(add2(5, 7))

12


In [58]:
function coordinates(x, y=0, z=0)
  println("($x, $y, $z)")
end

coordinates (generic function with 3 methods)

In [59]:
coordinates(1,0,2)

(1, 0, 2)
